# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_retargeting', '0006_campaign_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
