# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_retargeting', '0007_auto_20170504_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
