# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0008_auto_20170512_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='send_condition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
