# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_retargeting', '0011_auto_20170614_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='failure',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='send_condition',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
