# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='dictionary',
            field=models.TextField(default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(max_length=10000, verbose_name='Email body'),
        ),
    ]
