# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0003_email_failure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='to',
            new_name='to_email',
        ),
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
